### ISSUE TITLE
login to account

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#1]
**User Stories**
as a user, when I enter datadesk I should then be directed to the login page
as user, when I enter my details into the login system then I should be logged into my account and taken to datadesk

**Tasks**
- [x] create login interface
- [x] take in user email/username
- [x] take in user password
- [x] check whether user has entered username or email
- [x] check validity of user entered details
- [x] log user into account
