### ISSUE TITLE
Delete table

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#10]
**User story**
as a logged in user, when I choose to delete a table with a status of deleted then the table should be removed from the database and the meta table entry should be removed

**Tasks**
- [x] check for deleted mark in table
- [x] remove table from database if marked as deleted
- [x] remove meta table entry for removed table
- [x] if table marked as active mark as deleted
