### ISSUE TITLE
data summary

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#14]
**User story**
as a logged in use when I request to see a summary of a table that has been upload I should then be then to a summary page where a summary of the table is displayed

**Tasks**
- [x] display table name
- [x] display name of tabel in database
- [x] display upload date
- [x] display account that upload the entry
- [x] display the  source of the table
- [x] display the number of columns
- [x] display the number of rows 
- [x] display the details for columns
