### ISSUE TITLE
upload a csv file

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#15]
**User story:** 
as a logged in user, when I add a csv file to datadesk then the csv file will be saved in datadesk and converted to an array

**Tasks**
- [x] display upload interface for csv file
- [x] validate csv file and data
- [x] save array of headings for columns
- [x] split csv data into data array
- [x] save details of user who uploaded the table
