### ISSUE TITLE
list uploaded tables

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#17]
**User story**
as a logged in user, when I open datadesk a list of uploaded tables should be presented to me

**Tasks**
- [x] display a table of uploaded tables
- [x] display the id, name, name in database, upload date and status for each entry
- [x] display a link for fetching a json array of table data
