### ISSUE TITLE
fetch table data

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#19]
**User story**
as a logged in user, when I click the json link of a table, then I will be directed to a new tab where the data from the table will be displayed as a son array.

**Tasks**
- [x] add link to table item
- [x] write query to fetch table data by id
- [x] write api script that will echo a json formatted array
