### ISSUE TITLE
fetch table data as csv

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#25]
**User story**
as a logged in user, when I click the csv link of a table, then I will be directed to a new tab where the data from the table will be displayed as a csv array.

**Tasks**
- [x] add csv link to table item
- [x] write query to fetch table data by id
- [x] write api script that will echo a csv formatted array
