### ISSUE TITLE
account registration

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#5]
**User stories**
as a new user, when I open datadesk I should be taken to a registration page
as a new user, when I enter my details into the registration page then an account should created for me on datadesk

**Tasks**
- [x] create registration interface
- [x] take in name and surname
- [x] take in username
- [x] check that username isn't already being used
- [x] take in a password and a repeat of password for confirmation
- [x] check that both passwords match
- [x] create new account entry in account table
