### ISSUE TITLE
create cookie manager class

### ISSUE THREAD

**Issue by CiaranOtter** [mediahackza/datadesk#6]
**User story**
as a user, when I log in a cookie should be set in my browser to decrease the number of times I have to log in
as a returning user, when I open datadesk then my browser should be checked for a login cookie and attempt to log me in without prompting me for detail

**Tasks**
- [x] generate authentication token
- [x] set an authentication cookie for an account
- [x] read cookie from browser and start authentication process
